# Homebrew formula template for funcspec.
#
# The live formula is in the tap repo (https://github.com/narbs/homebrew-funcspec)
# and is regenerated by the `homebrew` job in .github/workflows/release.yml on
# every non-prerelease tag — version and SHA256 placeholders below are filled
# in from the published release's checksums.sha256 file.
#
# Users install via:  brew install narbs/funcspec/funcspec
class Funcspec < Formula
  desc "Command-line interface for FuncSpec"
  homepage "https://funcspec.net"
  version "0.0.0" # replaced by release workflow
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-x86_64-apple-darwin.zip"
      sha256 "PLACEHOLDER_X86_64_DARWIN_SHA256"
    end

    on_arm do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-aarch64-apple-darwin.zip"
      sha256 "PLACEHOLDER_AARCH64_DARWIN_SHA256"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "PLACEHOLDER_X86_64_LINUX_SHA256"
    end

    on_arm do
      url "https://github.com/narbs/funcspec-cli/releases/download/v#{version}/funcspec-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER_AARCH64_LINUX_SHA256"
    end
  end

  def install
    bin.install "funcspec"
  end

  def caveats
    <<~EOS
      funcspec has been installed. Run `funcspec login` to authenticate with funcspec.net.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funcspec --version")
  end
end
